### ISSUE TITLE
Plan does not get saved when deselecting a village 

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#73]
@onlyjsmith @TNgidi 

I believe this issue had popped up before, but I can't seem to remove villages from a plan

Bwa PROD, v 1.2.12, instance ID KASANE-TEST

Able to replicate in incognito mode

https://www.useloom.com/share/04cc4ef1527443b38685bb07ce9fa2ad

**Comment by onlyjsmith** [comment]
Thanks @sbabur - we’ll take a look.

**Comment by onlyjsmith** [comment]
@sbabur confirm we can reproduce

**Comment by onlyjsmith** [comment]
@sbabur Apologies for lack of updates here - this is fixed and released as part of v1.3.0. Can you validate in production?

**Comment by sbabur** [comment]
@onlyjsmith I am still seeing this issue in production, both after clearing my history and in incognito mode

https://www.useloom.com/share/16523cf1ebc445e7a66ab8e294d46cdc

**Comment by onlyjsmith** [comment]
@sbabur Thanks - will investigate right now. We can repro on production.

**Comment by TNgidi** [comment]
@sbabur please try testing it now

**Comment by sbabur** [comment]
Ok, its working now.

**Comment by onlyjsmith** [comment]
Thanks for confirming.

**Comment by TNgidi** [comment]
In that case it is ok to close this?

**Comment by sbabur** [comment]
Yes, can close
